Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: kp_06_july_2025

Resources:
  cfVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  cfSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-south-1a

  cfSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfVPC
      CidrBlock: 10.0.9.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-south-1b

  ec2WithVnc:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff91eb5c6fe7cc86
      InstanceType: t3.large
      KeyName: !Ref KeyPairName
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 30
          VolumeType: gp3
          DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt-get install -y apache2
          service apache2 start
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Please wait while startup script completes</title>
          </head>
          <body>
          <h1>Please wait while startup script completes..</h1>
          <script>
              function getRandomInt() {
                  return Math.floor(Math.random() * 256);
              }
              var color = 'rgb(' + getRandomInt() + ',' + getRandomInt() + ',' + getRandomInt() + ')';
              document.querySelector("h1").style.color = color;
              setInterval(function() {
                  location.reload();
              }, 1000);
          </script>
          </body>
          </html>
          EOF
          # Install Java 8 (OpenJDK) and Maven
          apt install -y openjdk-8-jdk maven

          # Install Tomcat 9
          cd /home/ubuntu
          wget -q https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
          tar -xzf apache-tomcat-9.0.85.tar.gz
          rm apache-tomcat-9.0.85.tar.gz
          chown -R ubuntu:ubuntu apache-tomcat-9.0.85
          
          # Install MySQL
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server mysql-client
          
          # Enable and start MySQL
          systemctl enable mysql
          systemctl start mysql
          
          # Configure MySQL users (idempotent)
          sudo mysql <<'MYSQL_EOF'
          -- Set root to password auth for automation
          ALTER USER 'root'@'localhost'
          IDENTIFIED WITH mysql_native_password BY 'root';
          
          -- Create ubuntu MySQL user if not exists
          CREATE USER IF NOT EXISTS 'ubuntu'@'localhost' IDENTIFIED BY 'ubuntu';
          GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'localhost' WITH GRANT OPTION;
          
          FLUSH PRIVILEGES;
          MYSQL_EOF
          public_ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Applications Installed</title>
          </head>
          <body>
          <h2>Installed Software</h2>
          <ul>
          <li>Java JDK (8)  </li>
          <li>Maven </li>
          <li>Tomcat (9) </li>
          <li>MySQL (8.0)  - <small>to launch mysql use this with password root 'mysql -u root -p'</small> </li>
          </ul>
          </body>
          </html>
          EOF
          systemctl enable apache2
          
          # Clone repository and setup symlink
          mkdir -p /home/ubuntu/Desktop
          chown ubuntu:ubuntu /home/ubuntu/Desktop
          cd /home/ubuntu/Desktop
          git clone https://github.com/devashish234073/cloud-pc-templates-marketplace
          ln -s /home/ubuntu/Desktop/cloud-pc-templates-marketplace/java/spring-mvc/persistence/mysql/spring-mvc-with-mysql-for-persistence /home/ubuntu/Desktop/spring-mvc-with-mysql-for-persistence
          chown -R ubuntu:ubuntu /home/ubuntu/Desktop/cloud-pc-templates-marketplace
          chown -h ubuntu:ubuntu /home/ubuntu/Desktop/spring-mvc-with-mysql-for-persistence
          
          # Build Project
          cd /home/ubuntu/Desktop/spring-mvc-with-mysql-for-persistence
          mvn install
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref cfSubnet1
          GroupSet:
            - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref cfVPC
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref cfVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cfVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref cfSubnet1
      RouteTableId: !Ref PublicRouteTable

  MyNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref cfVPC

  MyNetworkAclEntryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MyNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: false
      PortRange:
        From: 22
        To: 22

  MyNetworkAclEntryEgress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MyNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: true
      PortRange:
        From: 22
        To: 22
